### ISSUE TITLE
no video in the folder error

### ISSUE THREAD

**Issue by suyeon1109** [bw4sz/DeepMeerkat#45]
Traceback (most recent call last):
  File "DeepMeerkat/main.py", line 291, in worker
  File "Meerkat.py", line 38, in create_queue
ValueError: No videos in the supplied folder. If videos exist, ensure that they can be read by standard video CODEC libraries.
DeepMeerkat failed while running 

<img width="744" alt="Screenshot 2024-06-18 at 5 30 10 PM" src="https://github.com/bw4sz/DeepMeerkat/assets/97889490/24a8c93b-5722-4e80-bfcf-8b0c0076629c">

**Comment by suyeon1109** [comment]
<img width="815" alt="Screenshot 2024-06-18 at 5 30 54 PM" src="https://github.com/bw4sz/DeepMeerkat/assets/97889490/374fdca2-5060-4540-bf8d-afb1882c211c">
